# Site settings
title: Antonio Trento
description: An aspiring entrepreneur
# baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Antonio Trento
user_description: Hi, my name is Antonio, for some years now I have been dedicating my free time to trying to improve myself in Marketing, photography and above all I do coding. My goal is to be an entrepreneur and I already have a couple of interesting projects in the pipeline.
user_title: An aspiring entrepreneur
email: lantoniotrento@gmail.com
twitter_username: lantoniotrento
github_username:  antoniotrento
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
